# LD2410 Presense Sensor
uart:
  id: UART2
  rx_pin: ${rx_pin}
  tx_pin: ${tx_pin}
  baud_rate: 256000
  data_bits: 8
  stop_bits: 1
  parity: NONE


ld2410:
  id: my_ld2410
  uart_id: UART2


binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      id: has_target
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
      

sensor:
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
      id: detection_distance


switch:
  - platform: ld2410
    bluetooth:
      name: "Bluetooth"
    engineering_mode:
      name: "Engineering Mode"


number:
  - platform: ld2410
    g0:
      move_threshold:
        name: "G0 Move Threshold"
      still_threshold:
        name: "G0 Still Threshold"
    g1:
      move_threshold:
        name: G1 Move Threshold
      still_threshold:
        name: G1 Still Threshold
    g2:
      move_threshold:
        name: G2 Move Threshold
      still_threshold:
        name: G2 Still Threshold
    g3:
      move_threshold:
        name: G3 Move Threshold
      still_threshold:
        name: G3 Still Threshold
    g4:
      move_threshold:
        name: G4 Move Threshold
      still_threshold:
        name: G4 Still Threshold
    g5:
      move_threshold:
        name: G5 Move Threshold
      still_threshold:
        name: G5 Still Threshold
    g6:
      move_threshold:
        name: G6 Move Threshold
      still_threshold:
        name: G6 Still Threshold
    g7:
      move_threshold:
        name: G7 Move Threshold
      still_threshold:
        name: G7 Still Threshold
    g8:
      move_threshold:
        name: G8 Move Threshold
      still_threshold:
        name: G8 Still Threshold


button:
  - platform: ld2410
    factory_reset:
      name: Factory Reset
    restart:
      name: Restart Sensor
    query_params:
      name: Query Settings


select:
  - platform: ld2410
    distance_resolution:
      name: Distance Resolution
